import sys

with open('/home/aadish/Documents/typst/FactStamp/black_book_draft/04_System_Design/04_system_design.typ', 'r') as f:
    content = f.read()

replacements = [
    (
        "FactStamp's system design translates the requirements and conceptual models of Chapter 3 into a concrete, source-grounded architecture: eight functional modules, a Firestore document schema with server-enforced integrity constraints, the two core algorithms (Jaccard duplicate detection and weighted consensus scoring) that drive the platform's central value proposition, a fully custom user-interface layer, a defense-in-depth security architecture, and a formal test-case design. Every fact in this chapter is grounded in the deployed FactStamp codebase (`/home/aadish/Documents/Github/FactStamp`).",
        "Chapter 4 covers FactStamp's system design. It builds on the requirements and models from Chapter 3 to create a working architecture. This includes eight main modules, a Firestore database schema with server-side rules, and two algorithms (Jaccard duplicate detection and consensus scoring) that make the platform work. It also covers the custom user interface, security measures, and test cases. Everything in this chapter matches the actual code in the FactStamp repository (`/home/aadish/Documents/Github/FactStamp`)."
    ),
    (
        "FactStamp is decomposed into *8 core system modules*, each traceable to real source files. Chapter 3.5 (Preliminary Product Description) introduced them at a summary level; what follows is each module's internal responsibilities, key functions, and the calls between them across the claim lifecycle (submission #sym.arrow.r duplicate check #sym.arrow.r verification queue #sym.arrow.r consensus #sym.arrow.r shareable card #sym.arrow.r analytics), with Module 8 (Security & Notifications) cutting across all of the above.",
        "FactStamp has *8 core system modules*, and you can trace each one to specific source files. While Chapter 3.5 gave a quick summary, this section explains what each module actually does. It covers their main functions and how they interact during a claim's lifecycle (from submission #sym.arrow.r duplicate check #sym.arrow.r verification queue #sym.arrow.r consensus #sym.arrow.r shareable card #sym.arrow.r analytics). Module 8 handles security and notifications across the whole system."
    ),
    (
        "*Module 1 --- Authentication & Verifier Reputation.* Core files: `src/contexts/AuthContext.tsx`, `src/pages/SignIn.tsx`, `src/pages/SignUp.tsx`, `src/services/firebaseService.ts`. `AuthContext.tsx` wraps the Firebase Auth SDK in a React Context so every screen can read the current session and call `signIn`, `signUp`, `signInWithGoogle`, `signOut`, and `updateUser`. Registration supports both email/password and Google OAuth. On first sign-up, `firebaseService.ts` creates a `users/{uid}` Firestore document seeded with `reputation: 50` (the midpoint of the 0--100 scale), `totalVerifications: 0`, and `isAdmin: false` --- enforced server-side too, since `firestore.rules` only allows a self-created profile with exactly these seed values. Every other module depends on Module 1: Module 2 needs an authenticated `uid` to attach to a claim as `submittedBy`; Module 4 needs one to attach a verification as `verifierId`; Module 5 reads each verifier's *current* reputation directly out of their profile at the moment they vote.",
        "*Module 1: Authentication & Verifier Reputation.* Core files: `src/contexts/AuthContext.tsx`, `src/pages/SignIn.tsx`, `src/pages/SignUp.tsx`, `src/services/firebaseService.ts`. The `AuthContext.tsx` file puts the Firebase Auth SDK into a React Context. This lets any screen check the session or call functions like `signIn`, `signUp`, `signInWithGoogle`, `signOut`, and `updateUser`. Users can sign up with an email and password or a Google account. When someone registers, `firebaseService.ts` makes a `users/{uid}` document in Firestore. It sets their starting `reputation` to 50 (the middle of the 0 to 100 scale), `totalVerifications` to 0, and `isAdmin` to false. The `firestore.rules` file checks these starting values on the server so users cannot fake them. The rest of the system needs Module 1 to work. For example, Module 2 needs a user ID to label who submitted a claim. Module 4 uses the ID to record who verified a claim, and Module 5 checks a user's *current* reputation when they submit a vote."
    ),
    (
        "*Module 2 --- Forward Submission / Ingestion & OCR.* Core files: `src/pages/Submit.tsx`, `src/services/ocrService.ts`, `src/lib/imageCompression.ts`. Accepts a claim as raw pasted text or an uploaded WhatsApp forward screenshot. A screenshot passes through client-side compression (`imageCompression.ts`) and then Tesseract.js WebAssembly OCR (`ocrService.ts`, `createWorker`) entirely in-browser --- no image ever leaves the client. Raw OCR output is passed through `cleanExtractedOcrText()`, which strips WhatsApp chat chrome (timestamps, delivery checkmarks, carrier/battery status text). The user always reviews and can correct the cleaned text before submission. Once confirmed, `Submit.tsx` calls directly into *Module 3* before any `claims/{claimId}` document is created.",
        "*Module 2: Forward Submission / Ingestion & OCR.* Core files: `src/pages/Submit.tsx`, `src/services/ocrService.ts`, `src/lib/imageCompression.ts`. This module accepts a claim as copied text or an uploaded WhatsApp screenshot. If a user uploads a screenshot, the system compresses it using `imageCompression.ts`. Then it runs Tesseract.js WebAssembly OCR (`ocrService.ts`, `createWorker`) right in the browser. The image never leaves the user's device. The `cleanExtractedOcrText()` function cleans up the raw OCR text by removing WhatsApp elements like timestamps and delivery checkmarks. The user reviews and fixes the text before they submit it. After they confirm it, `Submit.tsx` connects to *Module 3* before creating a new `claims/{claimId}` document."
    ),
    (
        "*Module 3 --- Duplicate Detection Engine.* Core file: `src/lib/duplicateDetection.ts`. Implements token-level Jaccard word-overlap similarity: the incoming and every existing claim's text are normalized and tokenized (words $> 3$ characters only), and $J(A,B) = |S_A inter S_B| \\/ |S_A union S_B|$ is computed against each existing claim. A best match at or above the $0.75$ threshold blocks the submission and raises an inline duplicate warning linking to the existing claim instead of creating a duplicate (full algorithm in Section 4.3.3). Only a claim that clears no existing match proceeds to create a new `pending` document and enters Module 4's queue.",
        "*Module 3: Duplicate Detection Engine.* Core file: `src/lib/duplicateDetection.ts`. This part uses Jaccard word-overlap similarity to find duplicates. It cleans and splits the new claim and all existing claims into words longer than 3 characters. Then it calculates the similarity formula $J(A,B) = |S_A inter S_B| \\/ |S_A union S_B|$ for each existing claim. If a match scores 0.75 or higher, the system blocks the submission. It shows a warning with a link to the existing claim so it does not make a duplicate (you can see the full algorithm in Section 4.3.3). If the claim has no matches, the system creates a new `pending` document and sends it to Module 4."
    ),
    (
        "*Module 4 --- Verification Queue.* Core files: `src/pages/VerifyQueue.tsx`, `src/pages/VerifyDetail.tsx`, `src/contexts/ClaimsContext.tsx`. `VerifyQueue.tsx` lists every `pending` claim (admin-flagged claims surfaced first). `VerifyDetail.tsx` is the verifier's workbench: a verdict selection (`TRUE`/`FALSE`/`MISLEADING`/`UNVERIFIABLE` --- never `CONTESTED`, which is system-assigned only), a source URL whose domain is auto-classified into a source-quality rating by `determineSourceQuality()`, and a written explanation, gated by `validateVerdictExplanation()` in `src/lib/security.ts` (minimum 50 characters / 8 words, anti-spam checks --- full detail in Section 4.5). A valid submission appends to the claim's embedded `verifications[]` array and increments `verificationCount` by exactly 1, independently re-validated by `firestore.rules` (see Section 4.2.2). *The moment `verifications.length` reaches 3, `ClaimsContext.tsx` calls directly into Module 5* to compute the final verdict and confidence score in the same write.",
        "*Module 4: Verification Queue.* Core files: `src/pages/VerifyQueue.tsx`, `src/pages/VerifyDetail.tsx`, `src/contexts/ClaimsContext.tsx`. The `VerifyQueue.tsx` file lists all `pending` claims. It shows claims flagged by admins at the top. The `VerifyDetail.tsx` file gives verifiers their tools. They select a verdict (`TRUE`, `FALSE`, `MISLEADING`, or `UNVERIFIABLE`). They cannot choose `CONTESTED` because the system assigns that automatically. They add a source URL, and `determineSourceQuality()` grades the domain. They also write an explanation. The `validateVerdictExplanation()` function from `src/lib/security.ts` checks this text to make sure it has at least 50 characters and 8 words (more details in Section 4.5). A good submission adds to the `verifications[]` array in the claim and adds 1 to the `verificationCount`. The `firestore.rules` file double-checks this (see Section 4.2.2). *When `verifications.length` hits 3, `ClaimsContext.tsx` connects to Module 5*. It calculates the final verdict and score during the same save operation."
    ),
    (
        "Module 5 also owns *consensus expiry*: a periodic sweep finds any `pending` claim whose 7-day `consensusDeadline` has passed with `verificationCount < 3`, computes a confidence score from whatever verifications exist, and force-settles the verdict to `CONTESTED` --- the only path that produces this verdict, ensuring no claim sits in the queue indefinitely. Once `status` flips to `verified`, Module 5 triggers Module 8 to notify the submitter, and the claim becomes eligible for Module 6.",
        "Module 5 also handles *consensus expiry*. It regularly checks for any `pending` claim that passes its 7-day `consensusDeadline` with fewer than 3 verifications. It calculates a score from the verifications it has and changes the verdict to `CONTESTED`. This is the only way a claim gets that verdict, and it stops claims from being stuck in the queue forever. When the `status` changes to `verified`, Module 5 tells Module 8 to notify the person who submitted it. The claim is then ready for Module 6."
    ),
    (
        "*Module 6 --- Fact-Check Card Generator.* Core files: `src/components/FactCheckCard.tsx`, `src/pages/ClaimDetail.tsx`. Once a claim carries a final verdict and confidence score, `ClaimDetail.tsx` renders a styled DOM card that `html-to-image` rasterizes client-side into a 1080px-wide PNG --- the card is laid out at a 540px CSS width and captured at `pixelRatio: 2`, so its height is not fixed but grows with the claim text length and the number of cited sources --- via the browser's native SVG `foreignObject` path --- chosen because a legacy canvas parser could not interpret the `oklch()`/`oklab()` colors used throughout the design tokens. The user downloads and forwards the PNG back into the originating WhatsApp chat. This module is a pure consumer of Module 5's output.",
        "*Module 6: Fact-Check Card Generator.* Core files: `src/components/FactCheckCard.tsx`, `src/pages/ClaimDetail.tsx`. After a claim gets a final verdict and score, `ClaimDetail.tsx` creates a styled card. The `html-to-image` library turns this into a 1080px-wide PNG on the user's device. The code builds the card at 540px width and captures it at double resolution (`pixelRatio: 2`). Its height changes based on how much text and how many sources there are. It uses the browser's SVG `foreignObject` feature because older canvas parsers had trouble with the `oklch()` and `oklab()` colors in the design. The user downloads the PNG and sends it back to their WhatsApp chat. This module just uses the results from Module 5."
    ),
    (
        "*Module 7 --- Misinformation Analytics Dashboard.* Core files: `src/pages/Dashboard.tsx`, `src/components/DashboardChart.tsx`, `src/lib/weeklyReport.ts`. Deliberately a *public* route (see Section 4.4) so platform transparency is not gated behind login. `weeklyReport.ts` computes a rolling 7-day window: category distribution, verdict distribution, and a \"most-debunked\" trending list, rendered as Recharts visualizations with custom tooltips. Reads exclusively from claims Module 5 has already finalized (plus live `pending` counts for queue-size metrics); performs no writes.",
        "*Module 7: Misinformation Analytics Dashboard.* Core files: `src/pages/Dashboard.tsx`, `src/components/DashboardChart.tsx`, `src/lib/weeklyReport.ts`. This is a *public* page (see Section 4.4) so anyone can view platform data without logging in. The `weeklyReport.ts` file looks at the last 7 days of data. It calculates category breakdowns, verdict totals, and a list of top \"debunked\" claims. It shows these using Recharts graphs with custom pop-ups. It only reads claims that Module 5 finished, along with the current number of `pending` claims. It does not save any new data."
    ),
    (
        "*Module 8 --- System Security & Notifications.* Core files: `src/lib/security.ts`, `src/contexts/NotificationsContext.tsx`, `src/components/NotificationBell.tsx`, `firestore.rules`. The cross-cutting layer every other module calls into. `security.ts` supplies XSS sanitization, explanation anti-spam validation, upload validation, idle-session timeout, and login rate-limiting (full detail in Section 4.5). `NotificationsContext.tsx` and `NotificationBell.tsx` provide real-time in-app alerts that Module 5 fires into on claim resolution. `firestore.rules` is the server-side backstop for every client-side check in this module (see Sections 4.2.2 and 4.5).",
        "*Module 8: System Security & Notifications.* Core files: `src/lib/security.ts`, `src/contexts/NotificationsContext.tsx`, `src/components/NotificationBell.tsx`, `firestore.rules`. Every other module connects to this one. The `security.ts` file handles things like cleaning text inputs, blocking spam, checking file uploads, timing out idle sessions, and limiting login attempts (see Section 4.5). The `NotificationsContext.tsx` and `NotificationBell.tsx` files manage the live alerts that Module 5 triggers when a claim finishes. The `firestore.rules` file acts as the server-side backup for all the client-side security checks (see Sections 4.2.2 and 4.5)."
    ),
    (
        "FactStamp uses *Cloud Firestore*, a NoSQL document-oriented database, as its sole persistence layer --- there is no separate relational database or custom REST API. Five top-level collections hold all application state: `users`, `claims`, `notifications`, `reports`, and `audit_logs`. Every collection's shape is defined once in `src/lib/types.ts` and independently re-validated on every write by `firestore.rules`, so the schema below is mechanically enforced server-side, not merely a design intention.",
        "FactStamp stores all its data in *Cloud Firestore*, a NoSQL document database. It does not use a relational database or a custom REST API. Five main collections keep track of everything: `users`, `claims`, `notifications`, `reports`, and `audit_logs`. The `src/lib/types.ts` file defines what each collection looks like. The `firestore.rules` file checks these definitions on the server every time the system saves data. This means the rules listed below actually work in practice, rather than just being a plan."
    ),
    (
        "The constraints above are enforced server-side, by `firestore.rules`, which Firestore evaluates on every write attempt. A malicious or buggy client can send whatever payload it likes; any write that fails the matching rule is rejected before it reaches the database.",
        "The `firestore.rules` file enforces these rules on the server. Firestore checks them every time someone tries to save data. If a broken or harmful client app sends bad data, the server rejects it before it reaches the database."
    ),
    (
        "*Field-level write validation.* Every create/update rule inspects `request.resource.data` field-by-field rather than trusting the document as a whole. Creating a `claims/{claimId}` document requires `text.size()` between 10 and 2000, `category` against the fixed enum, `status == \"pending\"`, `verificationCount == 0`, and `verifications == []` --- a client cannot create a claim that is already verified, pre-seeded with fake verifications, or outside the text-length bounds.",
        "*Field-level write validation.* The rules check `request.resource.data` one field at a time instead of trusting the whole document. To make a new `claims/{claimId}` document, the `text.size()` must be between 10 and 2000 characters. The `category` has to match specific allowed words. The system also requires `status == \"pending\"`, `verificationCount == 0`, and an empty `verifications == []` list. This prevents anyone from submitting a claim that looks verified, has fake votes attached, or has too much text."
    ),
    (
        "*The `isAdmin()` helper.* Nearly every privileged write path gates on a single helper that performs a *live server-side read* of the caller's own `users/{uid}` document at write time:",
        "*The `isAdmin()` helper.* Most admin actions rely on a single helper function. This function reads the user's `users/{uid}` document on the server exactly when they try to save data:"
    ),
    (
        "Because `isAdmin` on a `users/{uid}` document can only be changed by an existing admin (the self-update branch requires the field stay unchanged), there is no path by which a normal user can grant themselves admin privileges, even by calling the Firestore SDK directly from a browser console.",
        "Only an existing admin can change the `isAdmin` setting on a `users/{uid}` document (regular users have to leave it exactly as it is). This stops regular users from giving themselves admin rights, even if they use the Firestore SDK from their browser console."
    ),
    (
        "*Append-exactly-one-verification-per-write.* The longest rule in the file governs adding a verification to a claim. It requires, simultaneously: `verificationCount` increases by exactly 1; the existing `verifications` array is fully preserved (`hasAll`); the newly appended element's `verifierId` equals the caller's own `uid`; that element's `verifierReputation` exactly matches the caller's *live* reputation value read at write time (preventing a client from inflating its own reported reputation to skew the consensus formula); the verdict is restricted to `TRUE`/`FALSE`/`MISLEADING`/`UNVERIFIABLE` (never `CONTESTED`); and `sourceUrl`/`explanation` satisfy their format and length bounds. This rule is the server-side mirror of Module 4's client-side `validateVerdictExplanation()` check (see Section 4.5) --- the client check exists for immediate UX feedback, but this rule is what actually prevents a forged or malformed verification from ever being persisted.",
        "*Append-exactly-one-verification-per-write.* The longest rule controls how people add verifications to a claim. It requires several things to happen at once. First, `verificationCount` must go up by exactly 1. Second, the old `verifications` list has to stay intact (`hasAll`). Third, the new vote's `verifierId` has to match the person saving it. Fourth, the `verifierReputation` must match the user's actual reputation at that exact moment (so no one can fake a high score). Next, the verdict must be `TRUE`, `FALSE`, `MISLEADING`, or `UNVERIFIABLE` (but not `CONTESTED`). Finally, the `sourceUrl` and `explanation` have to meet length and format rules. This server rule works just like Module 4's `validateVerdictExplanation()` check (see Section 4.5). The client check helps the user right away, but the server rule actually stops bad data from saving."
    ),
    (
        "*Immutability rules.* Several fields are permanently frozen once a claim is created, enforced via `isUnchanged()`/`identityUnchanged()` helpers: `text`, `category`, `submittedBy`, `submittedByName`, `createdAt`, `consensusDeadline`, and `imageUrl` cannot be altered by the \"add a verification\" or \"consensus expiry\" update paths --- only an admin override may touch them. `audit_logs` documents disallow `update` and `delete` entirely: an audit trail that could itself be edited or erased after the fact would defeat its own purpose.",
        "*Immutability rules.* The `isUnchanged()` and `identityUnchanged()` functions lock several fields permanently after a claim is created. Fields like `text`, `category`, `submittedBy`, `submittedByName`, `createdAt`, `consensusDeadline`, and `imageUrl` cannot change during verification or expiry. Only admins can edit them. The `audit_logs` collection blocks `update` and `delete` completely. An audit log would be useless if people could change or erase it later."
    )
]

for old, new in replacements:
    content = content.replace(old, new)

with open('/home/aadish/Documents/typst/FactStamp/black_book_draft/04_System_Design/04_system_design.typ', 'w') as f:
    f.write(content)
