= Conclusions

== Conclusion

FactStamp set out to close a specific gap identified in Chapter 1: WhatsApp forwards spread misinformation faster than either institutional fact-checkers or unstructured group-chat debunking can respond to it. What has been delivered is not a prototype or a design exercise but a fully functional, deployable web application --- every claim made in this report is traceable to a real file in the source tree at `/home/aadish/Documents/Github/FactStamp`. Revisiting the eight objectives set out in Section 1.2, each has been substantively achieved:

+ *Reduce the time-to-debunk.* Any user can submit a claim directly through the web app rather than waiting for an institutional fact-checker to notice a forward --- achieved by the multimodal submission pipeline (text or screenshot) that routes straight into the verification queue.
+ *Eliminate redundant verification effort.* Achieved through the Jaccard token-overlap duplicate detector (`src/lib/duplicateDetection.ts`, threshold $>= 0.75$), which recognizes a resubmitted claim under slightly different wording and returns the existing verdict instead of re-queuing it.
+ *Replace single-source trust with a distributed quorum.* Achieved: no single verifier or moderator can settle a verdict alone --- `src/contexts/ClaimsContext.tsx` and `src/services/firebaseService.ts` each enforce a minimum of three verifications before a claim can resolve, while `firestore.rules` independently re-validates every verification write server-side (Case C of the `claims/{claimId}` update rule) so that no verification can be forged or replaced by a client.
+ *Weight consensus by evidence quality, not headcount.* Achieved via the weighted confidence engine in `src/lib/confidenceScore.ts` --- `Confidence = 0.40×Agreement + 0.30×Reputation + 0.30×SourceQuality` --- so a unanimous vote from low-reputation verifiers citing weak sources scores lower than the same unanimous vote backed by trusted verifiers and authoritative citations.
+ *Make verified facts shareable in the native medium of the misinformation.* Achieved: the `html-to-image`-based card generator (`src/components/FactCheckCard.tsx`) exports a 1080px-wide PNG (a 540px-wide card rasterized at a 2#sym.times pixel ratio, its height growing with the claim text and source list) sized for WhatsApp, carrying the verdict, confidence score, and cited sources back into the same forward chains the original claim traveled through.
+ *Lower the barrier to submission for non-technical users.* Partially achieved --- client-side OCR (`src/services/ocrService.ts`, Tesseract.js) extracts text from an uploaded screenshot and strips WhatsApp chat chrome automatically, but this only works for English-script forwards (see Section 7.2).
+ *Build verifier accountability over time.* Achieved through the reputation system that raises or lowers a verifier's score based on alignment with eventual consensus, feeding directly back into the confidence-score weighting of every claim that verifier participates in.
+ *Give the public visibility into misinformation trends.* Achieved via the Recharts-powered analytics dashboard (`src/pages/Dashboard.tsx`, `src/lib/weeklyReport.ts`), surfacing category volume and rolling weekly "most-debunked" reporting.

Objective 6 is the only one delivered with a caveat rather than a clean achievement, and that caveat --- English-only OCR --- is treated honestly in Section 7.2 rather than glossed over.

=== Significance of the System

FactStamp's significance is not that it introduces a novel cryptographic primitive or a breakthrough machine-learning model --- it deliberately avoids AI-generated verdicts entirely, in favor of human, source-cited judgment. Its significance is architectural and social: it occupies a middle ground that neither of the two dominant fact-checking approaches covers.

Institutional fact-checkers (PIB Fact Check, AltNews, BOOM Live) are authoritative but structurally slow --- a small professional staff cannot scale to the volume of daily WhatsApp forwards across health, political, financial, and religious categories, and their long-form article format does not compete visually with an incendiary forward inside a chat thread. Ad-hoc group-chat debunking --- someone replying "this is fake" --- is fast but leaves no durable record, no source discipline, and no way to recognize the same claim the next time it resurfaces under different wording.

FactStamp sits between these two failure modes by being simultaneously:

- *Decentralized* --- verification authority is distributed across a community quorum rather than concentrated in an editorial desk, so throughput scales with the number of active verifiers rather than being capped by a fixed newsroom headcount.
- *Zero-infrastructure-cost* --- the entire platform runs on Firebase's free Spark tier plus static hosting, with no subscription server, no paid vision API, and no advertising-funded revenue model required to keep it running; the operating cost structure that makes institutional fact-checking hard to scale simply does not apply here.
- *Privacy-preserving* --- OCR runs entirely client-side via WebAssembly; a WhatsApp screenshot, which often contains other participants' names and phone numbers in its chat header, is never transmitted to a third-party cloud vision API. Verification stays on-device until the user chooses to submit only the extracted text.
- *Source-transparent* --- every verdict is backed by a visible, auditable chain of cited URLs and a mathematically defined confidence formula, in contrast to both the opaque internal review process of a newsroom and the zero-citation nature of a group-chat reply.

Taken together, FactStamp demonstrates that a scientifically defensible, quorum-governed verification process can be built and operated at genuinely zero infrastructure cost, without surrendering the human judgment and citation discipline that make a fact-check trustworthy in the first place. That is the project's core contribution as a BSc Information Technology capstone: not a single novel algorithm, but a coherent, fully working system that closes a real, named gap between two existing and inadequate alternatives.

== Limitations of the System

FactStamp is a genuinely working system, but honesty about its limitations is part of the dissertation, not an afterthought. The limitations below are real, verified against the source tree at `/home/aadish/Documents/Github/FactStamp`, and grouped by the kind of risk they represent rather than listed in arbitrary order.

=== Coverage & Accuracy Limitations

- *English-only OCR.* The bundled Tesseract.js model (`src/services/ocrService.ts`) only recognizes Latin/English script. A WhatsApp forward written in Devanagari or another regional Indic script cannot be auto-extracted from a screenshot --- the submitter must type the claim text manually instead of relying on OCR. Given how much Indian WhatsApp misinformation circulates in Hindi and other regional languages, this materially narrows the population of forwards the system can ingest frictionlessly.
- *Lower OCR accuracy than commercial cloud vision APIs.* Running OCR entirely client-side via WebAssembly was a deliberate privacy and cost trade-off (Section 2.5), but it is still a real accuracy limitation, especially on low-resolution or heavily compressed WhatsApp screenshots, where a cloud vision model such as Google Cloud Vision would extract text more reliably. `cleanExtractedOcrText()` mitigates WhatsApp-chrome noise, and the user can always hand-correct the extracted text, but the underlying recognition quality is capped by what a browser-side WASM model can do.
- *No direct WhatsApp Business API integration.* FactStamp does not intercept or read WhatsApp messages automatically. A user must manually copy-paste text or upload a screenshot into the web app --- the system has no chatbot or Business API listener sitting inside WhatsApp itself. This adds a submission-friction step that a native in-app integration would remove.

=== Trust & Governance Limitations

- *Quorum consensus assumes baseline good-faith participation.* The 3-verifier quorum and reputation-weighted confidence score are designed to resist Sybil-style manipulation, but the design still assumes a community of largely good-faith participants. In a small early user base, a coordinated set of adversarial-only accounts could theoretically stack a quorum before organic reputation differentiation has had a chance to down-weight them. Reputation weighting mitigates this risk over time but does not eliminate it, particularly during the platform's early-adoption phase when the pool of verifiers is small.
- *Source-quality scoring depends on a small hardcoded domain list.* `src/lib/confidenceScore.ts` classifies a cited source as high, medium, or low quality using fixed domain lists (e.g., `who.int`, `pib.gov.in` as high-quality; `bbc.com` and similar outlets as medium-quality). Any legitimate, credible source domain that is not on that hardcoded list --- a regional newspaper, a specialized medical journal, a state government portal not yet added --- defaults to "low" quality by omission, even when it is a genuinely reliable citation. This can unfairly under-weight a valid verification simply because its source domain was never added to the list.

=== Architectural & Scaling Limitations

- *Quorum threshold duplicated as a bare literal across the application layers.* The "3 verifications required" rule is never expressed as a single named constant: it appears as a hardcoded `>= 3` comparison in six separate places across the client-side `ClaimsContext.tsx` and the `firebaseService.ts` service layer. This is a genuine architectural fragility: if the quorum number were ever changed, every one of those locations would need to be updated in lockstep, and a missed update in any one of them would put the queue, the consensus trigger, and the expiry sweep out of agreement with each other. The gap is widened by the fact that `firestore.rules` validates the _shape_ of each verification write (Case C of the `claims/{claimId}` update rule) but does not itself enforce the count --- so the quorum is, in the end, a client-enforced invariant rather than a server-enforced one.
- *No automated test suite.* `package.json` defines only `dev`, `build`, `preview`, `typecheck`, `emulators` (and its `:persist`/`:export` variants), `seed:db`, `create:admin`, and `create:user` --- there is no `test` script and no unit or integration test files anywhere in the codebase. Correctness is currently verified through manual/structured testing rather than a CI-enforced automated suite, which means regressions in core logic (duplicate detection, the consensus formula, security-rule behavior) rely on a human tester noticing them rather than a test pipeline catching them automatically before deployment.
- *Image storage capped by the Firestore-embedded approach.* To stay within the Firebase free tier, uploaded screenshots are compressed and stored as base64 strings directly inside the claim's Firestore document (`src/lib/imageCompression.ts`), rather than in a proper object-storage bucket. This caps usable image payloads at roughly 800 KB per claim and would not scale gracefully to a large volume of images --- Firestore document size limits and per-document read costs both work against this approach at scale, even though `storage.rules` already defines a `claim_screenshots` path --- currently an unused, locked-down placeholder that no application code path writes to --- which could carry that load if the flow were migrated to use it as the primary path.

== Future Scope of the Project

The limitations identified above map directly onto a concrete roadmap rather than open-ended wishful features. The items below are organized into near-term work (extending or hardening what already exists) and long-term work (larger architectural or platform changes), each with a reason it would matter.

=== Near-Term Scope

- *Multi-language OCR (Devanagari and other Indic scripts).* Extending the Tesseract.js pipeline with additional trained language models would directly address the English-only OCR limitation and open the system to the large volume of Hindi and regional-language WhatsApp forwards that currently require manual transcription --- this is arguably the single highest-impact near-term change given how much Indian misinformation circulates outside English.
- *Expanding the source-quality domain list into a maintained, community-curatable credibility database.* Rather than a small hardcoded high/medium/low domain list in `confidenceScore.ts`, a maintained and community-extensible credibility database would let legitimate regional or specialized sources be added over time instead of defaulting to "low quality" by omission --- this directly closes the source-quality gap without requiring a redesign of the confidence formula itself.
- *Consolidating the quorum threshold into a single source of truth.* Refactoring the hardcoded `>= 3` checks that currently sit as bare literals in the client Context and the service layer into a single shared constant (or a Firestore-remote-config value read by every layer, including the security rules) would remove the architectural fragility flagged above and make any future quorum-size change (e.g., raising it as the platform scales) a one-line change instead of a six-location, easy-to-desynchronize edit. Promoting the same value into `firestore.rules` would additionally turn the quorum from a client-enforced invariant into a server-enforced one.
- *An appeal / re-review workflow for CONTESTED claims.* Claims that expire into `CONTESTED` after the 7-day consensus deadline currently have no path back into active review. A structured re-review or appeal flow would give genuinely ambiguous claims a second pass with fresh verifiers, rather than leaving them permanently unresolved --- this matters because a claim stuck as `CONTESTED` provides no more clarity to the public than no fact-check at all.
- *A basic automated test suite.* Adding unit tests for the two most consequential pieces of logic --- the Jaccard duplicate-detection threshold and the weighted consensus formula --- plus integration tests against the Firebase Local Emulator Suite (already used for `npm run emulators`) would close the testing gap and let regressions in core scoring logic be caught before deployment rather than by a human noticing incorrect verdicts in production.

=== Long-Term Scope

- *WhatsApp Business API / chatbot-based direct submission.* Integrating with the WhatsApp Business API so a user could forward a suspicious message directly to a FactStamp bot number, rather than manually copying text or uploading a screenshot into the web app, would remove the submission-friction step identified above and meet users inside the exact medium the misinformation is already traveling through.
- *Migrating large images to Firebase Storage as the primary flow.* The `storage.rules` file already defines a `claim_screenshots` path, but no application code path writes to it, and the primary image flow still compresses screenshots to base64 inside Firestore documents. Migrating to Storage-backed images as the default (rather than leaving that rule as an unused placeholder) would remove the roughly 800 KB per-claim image cap and let the platform scale to a much larger image volume without hitting Firestore document-size or read-cost constraints.
- *A mobile app wrapper (React Native or installable PWA).* Packaging the existing web application as an installable Progressive Web App, or a thin React Native wrapper, would give FactStamp a persistent home-screen presence and access to native push notifications, which matters because most WhatsApp forwarding happens from a phone, not a desktop browser tab that has to be reopened.
- *A browser extension for one-click submission.* A companion browser extension that lets a user right-click any webpage or chat screenshot and submit it to FactStamp directly, without navigating to the web app first, would reduce submission friction for the growing share of misinformation that first surfaces on the open web before being forwarded into WhatsApp groups.
- *Push notifications (web push) instead of only in-app notifications.* Currently, a submitter learns their claim reached consensus only by returning to the app. Web push notifications would close that loop proactively, which matters for the core objective of getting a verified debunk back into circulation as quickly as possible after consensus is reached.
- *Multi-tenant support for other messaging platforms (Telegram, SMS forwards).* The underlying submission, duplicate-detection, and quorum-consensus pipeline is not conceptually WhatsApp-specific --- extending claim ingestion to Telegram forwards or SMS-based chain messages would let the same verification infrastructure serve other closed, forward-driven misinformation channels that share WhatsApp's structural problem of being invisible to search-engine-indexed fact-checking.
